alias ls='ls -G'
alias l='ls -G'
alias 'cd..'='cd ..'
alias be='bundle exec'
alias bi='bundle install'
alias biwp='bundle install --without production'
alias grep='grep --color=auto -n'
alias egrep='egrep --color=auto -n'
alias g='git'
alias gti='git'
alias gt='git'
alias ag='ag -S --stats'
