alias ll='ls -l'
alias be='bundle exec'
alias g='git'
alias gti='git'
alias gt='git'
alias gcd='cd `git rev-parse --show-toplevel`'
alias ghqget='ghq get --shallow --no-recursive'
alias jqc='jq -C . |less -R'
alias k='kubectl'
alias kc='kubectx'
alias kn='kubens'
alias kd='kubectl describe'
alias yless='jless --yaml'
alias lg='lazygit'

if [[ "$(command -v eza)" ]]; then
  alias ls='eza'
  alias la='eza -a'
  alias ll='eza -aal'
  alias lt='eza -T -L 3 -a -I "node_modules|.git|.cache"'
  alias lta='eza -T -a -I "node_modules|.git|.cache" --color=always | less -r'
fi
